#!/usr/bin/python
#coding: utf8
"""
cluster

Homework 5: http://www.csee.umbc.edu/~nicholas/676/term%20project/hw5.html

Author: Primal Pappachan, primal1@umbc.edu

Usage:
  cluster <files>
  cluster -h | --help
  cluster --version

Options:
  -h --help     Show this screen.
  --version     Show version.

"""

import nltk, unicodedata, HTMLParser
import os, sys, re
import collections
import random, math
from pprint import pprint
import operator
from docopt import docopt


class Similarity:
    """Similarity Matrix for Document Clustering"""
    def __init__(self):
        self.sim_matrix = collections.defaultdict(dict) #document : document : cosine similarity
        self.max_sim = [] #similarity scores as tuples (score, d1, d2)
        self.active_clusters = {} #keeps track of active clusters

    def similarity_heap(self, d1):
        """ Adds the maximum similarity score corresponding to d1 to max_sim """
        flag = 0
        #import ipdb; ipdb.set_trace()
        for d2 in self.sim_matrix[d1].keys():
            maximum = (flag, d1, d2)
            if d1 != d2: #ignoring similarity with itself
                if self.active_clusters[d1] + self.active_clusters[d2] == 2: #checking if cluster is active
                    score = self.sim_matrix[d1][d2]
                    if score > flag and score != 1:
                        flag = score
                        maximum = (flag, d1, d2)
        self.max_sim.append(maximum)

    def get_high_sim(self):
        """ Returns tuple (score, d1, d2) with largest similarity score """
        return max(self.max_sim)

    def group_link_avg(self):
        """Recompute distances"""
        pass

    def update_clusters():
        """Make it N-1 clusters"""
        pass



class Index:
    """Variables for building index"""
    def __init__(self):
        self.weights = collections.defaultdict(dict) #term : document : normalized term weight

    def cosine_denominator(self, doc):
        result = sum(v **2 for v in self.weights[doc].values())
        return math.sqrt(result)

    def product(self, doc1, doc2):
        keys = self.weights[doc1].viewkeys() &  self.weights[doc2].viewkeys()
        result = sum (self.weights[doc1][k] * self.weights[doc2][k] for k in keys)
        return result

class Calcwts:
    """ Methods and variables for term weight computation """
    def __init__(self):
        self.model = collections.defaultdict(dict) #document : term : frequency
        self.total_docs = 0 #Total Number of documents
        self.avg_doclen = 0 #Average length of documents
        self.inverse_doc_freq = {} #Inverse Document Frequency

    def freq(self, tokens):
        index = {}
        for (term, freq) in collections.Counter(tokens).iteritems():
            index[term] = freq
        return index

    def tf(self, term_freq, total_freq):
        """Computes term frequency"""
        return term_freq / float (total_freq)

    def idf(self, word):
        """ Computes Inverse Document frequency """
        return math.log(self.total_docs / float(self.inverse_doc_freq[word]))

    def tf_idf(self, word, doc, doclen):
        term_freq = self.model[doc][word]
        tf_value = self.tf(term_freq, doclen)
        idf_value = self.idf(word)
        return tf_value * idf_value

    def bm25_ranking(self, word, doc, doclen):
        """ Calculates BM25 with K1 = 1 and S1 = K1 + 1 """
        k1 = 1
        s1 = k1 + 1
        freq = self.model[doc][word]
        return s1 * (freq / ( ( (k1 * doclen ) / self.avg_doclen ) + freq ))

class Tokenization:
    """Methods and variables for tokenization"""
    def __init__(self):
        self.html_parser = HTMLParser.HTMLParser()
        self.tokenizer = nltk.tokenize.RegexpTokenizer("[\w’]+", flags=re.UNICODE)
        self.stopwords = open('stoplist.txt').read().splitlines() #from file
        try:
            self.stopwords.extend(nltk.corpus.stopwords.words('english')) #from nltk corpus
        except Exception:
            pass

    def clean_html(self, raw):
        """
        Clean the raw string.
        It removes the html markup, formatting as well as non alphanumeric characters.
        Return string.
        """
        cleaned = nltk.clean_html(raw)
        cleaned = cleaned.decode('utf8', 'ignore')
        cleaned = self.html_parser.unescape(cleaned)
        cleaned = unicodedata.normalize('NFKD', cleaned).encode('latin-1','ignore')
        return cleaned

    def extract_tokens(self, cleaned):
        """
        Converts cleaned text to a vocabulary.
        Returns dictionary.
        """
        text = self.tokenizer.tokenize(cleaned)
        #Limiting words to have size > 2 and < 20 and not numbers
        words = [w.lower() for w in text if len(w) > 2 and len(w) < 20 and not w.isdigit()]
        #Stopwords removal
        words = [word for word in words if word not in self.stopwords]
        return words

def file_id(doc):
    return os.path.basename(doc)

def main(args):
    input_path= args['<files>']
    number_of_files = 503
        
    tkr = Tokenization()

    list_of_files = []
    for (dirpath, dirnames, filenames) in os.walk(input_path):
        for filename in filenames:
            list_of_files.append(os.sep.join([dirpath, filename])) #List of complete files
    random.shuffle(list_of_files) #Randomizing the order of files in the list

    print "Phase 1: Starting tokenization"
    cwts = Calcwts()
    for i in range(0, number_of_files): # Slicing the list of files as per Number of files
        filename = list_of_files[i]
        file_obj = open(filename)
        raw_string = file_obj.read()
        cleaned = tkr.clean_html(raw_string) #cleaning raw html string
        tokens = tkr.extract_tokens(cleaned) #tokenization
        token_frequency = cwts.freq(tokens) #computing frequency of extracted tokens
        for token in tokens:
            cwts.model[filename][token] = token_frequency[token]
    print "Tokenization completed"

    vocabulary = []
    for docs in cwts.model.values():
        vocabulary.extend(docs.keys()) #complete vocabulary with repetitions; for computing document frequency in idf
    cwts.inverse_doc_freq = cwts.freq(vocabulary)

    print "Phase 2: Term Weighting"
    cwts.total_docs = len(cwts.model.keys())
    for d in cwts.model.keys():
        cwts.avg_doclen += sum(cwts.model[d].values())
    cwts.avg_doclen /= float(cwts.total_docs) #average document length

    inv_index = Index()
    for i in range(0, number_of_files):
        doc = list_of_files[i]
        doclen = sum(cwts.model[doc].values()) #length of document
        for word in cwts.model[doc].keys():
            term_weight = "%.8f" %(cwts.tf_idf(word, doc, doclen))
            inv_index.weights[doc][word] = eval(term_weight) #Creating the [term][document] weight dictionary
    print "Term Weighting completed"

    print "Phase 5: Computing Similarity scores"
    #Building singleton clusters based on cosine similarity
    SimObj = Similarity()
    for i in range(0, number_of_files):
        doc1 = list_of_files[i]
        denominator_doc1 = inv_index.cosine_denominator(doc1)
        for j in range(i, number_of_files):
            doc2 = list_of_files[j]
            SimObj.sim_matrix[doc1][doc2] = inv_index.product(doc1, doc2) / (denominator_doc1 * inv_index.cosine_denominator(doc2))
        SimObj.active_clusters[doc1] = 1

    import ipdb; ipdb.set_trace()
    print "Clustering Documents"
    A = [] #assembles clustering as sequence of merges

    for i in xrange(0, number_of_files):
        doc1 = list_of_files[i]
        SimObj.similarity_heap(doc1)
    
    print SimObj.get_high_sim()    
    
    # for k in xrange(0, number_of_files):
    #     score, d1, d2 = SimObj.get_high_sim()
    #     A.append((d1, d2)) #storing merge
    #     for j in range(0, number_of_files):

    #     recalculate similiarties
    #     deactivate other cluster
    # #import ipdb; ipdb.set_trace()
    #Clustering - first iteration
    #for i 

if __name__ == "__main__":
    arguments = docopt(__doc__, version='Cluster 1.0')
    main(arguments)
